import Router from '@koa/router'
import * as ctrl from '../controllers/sessions'
import { requireAdmin, requireSuperAdmin } from '../public/auth'

export const sessionRoutes = new Router()

sessionRoutes.get('/api/studio/sessions/conversations', ctrl.listConversations)
sessionRoutes.get('/api/studio/session-categories', ctrl.listCategories)
sessionRoutes.post('/api/studio/session-categories', ctrl.createCategory)
sessionRoutes.patch('/api/studio/session-categories/:id', ctrl.renameCategory)
sessionRoutes.delete('/api/studio/session-categories/:id', ctrl.removeCategory)
sessionRoutes.get('/api/studio/sessions/conversations/:id/messages', ctrl.getConversationMessages)
sessionRoutes.get('/api/studio/sessions/conversations/:id/messages/paginated', ctrl.getConversationMessagesPaginated)
sessionRoutes.get('/api/studio/sessions', ctrl.list)
sessionRoutes.get('/api/studio/sessions/count', ctrl.count)
sessionRoutes.get('/api/studio/sessions/hermes', ctrl.listHermesSessions)
sessionRoutes.get('/api/studio/sessions/hermes/groups', ctrl.listHermesSessionGroups)
sessionRoutes.get('/api/studio/sessions/hermes/:id', ctrl.getHermesSession)
sessionRoutes.post('/api/studio/sessions/hermes/:id/import', ctrl.importHermesSession)
sessionRoutes.post('/api/studio/sessions/hermes/:id/continue-in-web', ctrl.continueHermesSessionInWeb)
sessionRoutes.get('/api/studio/search/sessions', ctrl.search)
sessionRoutes.get('/api/studio/sessions/search', ctrl.search)
sessionRoutes.get('/api/studio/sessions/usage', ctrl.usageBatch)
sessionRoutes.get('/api/studio/usage/stats', ctrl.usageStats)
sessionRoutes.get('/api/studio/sessions/context-length', ctrl.contextLength)
sessionRoutes.get('/api/studio/sessions/:id/identity', ctrl.getSessionIdentity)
sessionRoutes.get('/api/studio/sessions/:id/context', ctrl.getContext)
sessionRoutes.get('/api/studio/sessions/:id/workspace-run-changes', requireSuperAdmin, ctrl.listWorkspaceRunChanges)
sessionRoutes.get('/api/studio/sessions/:id/workspace-run-changes/:changeId/files/:fileId', requireSuperAdmin, ctrl.getWorkspaceRunChangeFile)
sessionRoutes.get('/api/studio/sessions/:id/workspace-files/list', requireSuperAdmin, ctrl.listWorkspaceFiles)
sessionRoutes.get('/api/studio/sessions/:id/workspace-file/diff', requireSuperAdmin, ctrl.diffWorkspaceFile)
sessionRoutes.get('/api/studio/sessions/:id/workspace-file/read', requireSuperAdmin, ctrl.readWorkspaceFile)
sessionRoutes.get('/api/studio/sessions/:id/workspace-file/content', requireSuperAdmin, ctrl.readWorkspaceFileContent)
sessionRoutes.put('/api/studio/sessions/:id/workspace-file/write', requireSuperAdmin, ctrl.writeWorkspaceFile)
sessionRoutes.post('/api/studio/sessions/:id/workspace-file/mkdir', requireSuperAdmin, ctrl.mkdirWorkspaceFile)
sessionRoutes.delete('/api/studio/sessions/:id/workspace-file/delete', requireSuperAdmin, ctrl.deleteWorkspaceFile)
sessionRoutes.post('/api/studio/sessions/:id/workspace-file/rename', requireSuperAdmin, ctrl.renameWorkspaceFile)
sessionRoutes.post('/api/studio/sessions/:id/workspace-file/copy', requireSuperAdmin, ctrl.copyWorkspaceFile)
sessionRoutes.get('/api/studio/sessions/:id', ctrl.get)
sessionRoutes.get('/api/studio/sessions/:id/export', ctrl.exportSession)
sessionRoutes.get('/api/studio/sessions/:id/usage', ctrl.usageSingle)
sessionRoutes.delete('/api/studio/sessions/:id', ctrl.remove)
sessionRoutes.post('/api/studio/sessions/batch-delete', ctrl.batchRemove)
sessionRoutes.post('/api/studio/sessions/:id/rename', ctrl.rename)
sessionRoutes.post('/api/studio/sessions/:id/archive', ctrl.archive)
sessionRoutes.post('/api/studio/sessions/:id/unarchive', ctrl.unarchive)
sessionRoutes.post('/api/studio/sessions/:id/push-enabled', ctrl.setPushEnabled)
sessionRoutes.post('/api/studio/sessions/:id/workspace', requireAdmin, ctrl.setWorkspace)
sessionRoutes.post('/api/studio/sessions/:id/category', ctrl.setCategory)
sessionRoutes.post('/api/studio/sessions/:id/model', requireAdmin, ctrl.setModel)
sessionRoutes.post('/api/studio/sessions/:id/reasoning-effort', requireAdmin, ctrl.setReasoningEffort)
sessionRoutes.get('/api/studio/workspace/folders', requireSuperAdmin, ctrl.listWorkspaceFolders)
sessionRoutes.post('/api/studio/workspace/folders', requireSuperAdmin, ctrl.createWorkspaceFolder)
sessionRoutes.post('/api/studio/workspace/folders/rename', requireSuperAdmin, ctrl.renameWorkspaceFolder)
sessionRoutes.delete('/api/studio/workspace/folders', requireSuperAdmin, ctrl.deleteWorkspaceFolder)
